"use client";
import {useMemo,useState} from "react";

type Status="BEKRÆFTET"|"BETINGET"|"KANDIDAT"|"OBSERVATION"|"FROSSET"|"FALSIFICERET";
type Case={title:string,status:Status,relations:string[],finding:string,counter:string};
type World={id:string,glyph:string,title:string,subtitle:string,intro:string,color:string,cases:Case[]};

const worlds:World[]=[
 {id:"life",glyph:"◌",title:"Liv",subtitle:"Biologi & evolution",color:"#71d8b5",intro:"Liv læst som vedligeholdt udveksling: grænser, symbiose, regulering og tilpasning.",cases:[
  {title:"Den levende membran",status:"BEKRÆFTET",relations:["Betinget adgang","Udveksling","Feedback"],finding:"Membranen bevarer forskel ved selektivt at tillade passage — åbenhed og afgrænsning eksisterer samtidigt.",counter:"Den relationelle læsning erstatter ikke biokemiske mekanismer; den sammenfatter deres funktionelle struktur."},
  {title:"Symbiose",status:"BETINGET",relations:["Udveksling","Stabilisering","Identitet"],finding:"Organismers muligheder og identitet kan vedligeholdes gennem afhængigheder på tværs af artsgrænser.",counter:"Ikke alle relationer er gensidigt gavnlige, og symbiose alene viser ikke en universel kerne."},
  {title:"Homeostase",status:"BEKRÆFTET",relations:["Residual","Feedback","Recoverability"],finding:"Afvigelser påvirker senere regulering; stabilitet er aktiv vedligeholdelse, ikke stilstand.",counter:"Analogier til sociale eller tekniske systemer kræver særskilt test."}]},
 {id:"pathology",glyph:"⌁",title:"Krop",subtitle:"Patologi & recoverability",color:"#ff8f9f",intro:"Sygdom undersøgt som ændret adgang, belastning, kompensation og mulige veje tilbage.",cases:[
  {title:"Kompensation før kollaps",status:"KANDIDAT",relations:["Spændingsretning","Stabilisering","Residual"],finding:"Et symptom kan være systemets midlertidige svar på en underliggende forskydning frem for den oprindelige fejl.",counter:"Skal operationaliseres sygdomsspecifikt; må ikke bruges som klinisk konklusion alene."},
  {title:"Recoverability",status:"BETINGET",relations:["Feedback","Recoverability","Betinget adgang"],finding:"Robusthed kan måles som bevaret adgang til levedygtige næste tilstande, ikke kun øjeblikkelig normalitet.",counter:"Kliniske tærskler og outcomes mangler endnu i flere domæner."},
  {title:"Protesedemo v1.1",status:"BETINGET",relations:["Probe","Stabilisering","Recoverability"],finding:"I simulerede perturbationer valgte M.E.M.I. stabilisér → undersøg → greb, hvor baseline gentog stabilisering.",counter:"Det er en kontrolleret demo, ikke patientdata eller klinisk validering."}]},
 {id:"human",glyph:"◎",title:"Menneske",subtitle:"Samfund & ansvar",color:"#f3bf68",intro:"Institutioner og fællesskaber set gennem adgang, beslutninger, ansvar og mulighed for reparation.",cases:[
  {title:"Kontrol eller robusthed",status:"KANDIDAT",relations:["Recoverability","Ansvar","Feedback"],finding:"Sikkerhed kan søges gennem evnen til at opdage, svare og vende tilbage — ikke kun gennem mere kontrol.",counter:"Konsekvenser varierer med institution, magt og skadepotentiale."},
  {title:"Negativt udfald som viden",status:"BEKRÆFTET",relations:["Residual","Afgrænsning","Ansvar"],finding:"Et ærligt nulresultat afgrænser mulighedsrummet og beskytter senere beslutninger mod ønsketænkning.",counter:"Kun hvis kriterier og frysestatus fastholdes efter resultatet."}]},
 {id:"religion",glyph:"✧",title:"Fortælling",subtitle:"Religion & overgang",color:"#c9a8ff",intro:"Traditioner følges hver for sig; først derefter vises strukturelle gentagelser.",cases:[
  {title:"Ra · Ma’at · Apep",status:"OBSERVATION",relations:["Orden","Overgang","Gentagelse"],finding:"Den egyptiske cyklus kan læses som vedligeholdelse gennem tolv overgangsfelter, ikke som én afsluttet skabelse.",counter:"Det er en relationel fortolkning; historiske og filologiske læsninger skal forblive synlige."},
  {title:"Død · overgang · genkomst",status:"KANDIDAT",relations:["Overgang","Lukket–åben","Gentagelse"],finding:"Flere traditioner organiserer forandring omkring tab af form, passage og ny manifestation.",counter:"Lighed i struktur er ikke bevis for fælles oprindelse eller identisk betydning."},
  {title:"Udeladte skrifter",status:"KANDIDAT",relations:["Adgang","Grænse","Efterspor"],finding:"Kanonisering kan undersøges som en proces, der både bevarer og lukker mulige fortolkningsveje.",counter:"Hvert skrift kræver selvstændig kildehistorie; kategorien må ikke homogeniseres."}]},
 {id:"signs",glyph:"◐",title:"Tegn",subtitle:"Phaistos & gamle skrifter",color:"#f2d46f",intro:"Først form, position og rytme. Fortolkning åbnes som et separat lag.",cases:[
  {title:"Phaistos · observationslag",status:"OBSERVATION",relations:["Sekvens","Gentagelse","Asymmetri"],finding:"Tegn registreres efter side, gruppe, position, naboskab, afstand og retning uden at tildele sproglig betydning.",counter:"Struktur alene oversætter ikke skiven."},
  {title:"Phaistos · relationel læsning",status:"KANDIDAT",relations:["Rytme","Overgang","Centrum"],finding:"Gentagelser og gruppeskift undersøges som mulige markører for faser eller overgange.",counter:"Læsningen er en hypotese og skal holdes adskilt fra det rå observationslag."}]},
 {id:"earth",glyph:"◇",title:"Jord",subtitle:"Landskab & efterspor",color:"#7ed0e6",intro:"Terrænets relationer først; menneskets spor lægges på bagefter.",cases:[
  {title:"Passage–barriere",status:"BETINGET",relations:["Passage–barriere","Gentagelse","Selvforstærkning"],finding:"Kali Gandaki og Gibraltar viser uafhængigt: barriere, smal passage og koncentreret bevægelse uden menneskelige kategorier.",counter:"Selvforstærkning er plausibel, men ikke fuldt kausalt isoleret i begge cases."},
  {title:"Doggerland",status:"BETINGET",relations:["Tilgængelighed","Vand–jord","Efterspor"],finding:"Efterspor vurderes inden for en verificeret tilgængelighedsperiode frem for ud fra nutidens kystlinje.",counter:"Bevaring og datadækning kan forme det observerede mønster."},
  {title:"Bornholm · fire strukturklasser",status:"FALSIFICERET",relations:["Residual","Afgrænsning","Efterspor"],finding:"Fire forventede mønstre holdt ikke under de fastlagte kriterier; nulresultaterne er bevaret.",counter:"Afviser de testede klasser — ikke enhver mulig relation på Bornholm."},
  {title:"Gotland · omvendt effekt",status:"BETINGET",relations:["Geologi","Efterspor","Asymmetri"],finding:"Det observerede mønster vendte den forventede kalkstensretning og blev bevaret som selvstændigt resultat.",counter:"Alternative forklaringer som bevaring og bosætningshistorik skal testes."},
  {title:"South Clare / Burren",status:"FROSSET",relations:["Geologi","Afgrænsning","Residual"],finding:"Den brede zone blev afvist, fordi den dækkede for meget. Den smalle kant er kun indikativ.",counter:"Ingen diskret geologisk overgangszone med tilstrækkeligt n blev fundet til preregistrering."},
  {title:"Høj–lav → vand–jord → passage",status:"KANDIDAT",relations:["Gradient","Vand–jord","Passage–barriere"],finding:"En sammensat kæde, hvor terrænets gradient organiserer vand og dermed sandsynlige passager og efterspor.",counter:"Leddene er ikke endnu testet som én samlet kausal kæde."}]},
 {id:"space",glyph:"⊙",title:"Rum",subtitle:"Kosmologi & observation",color:"#83a8ff",intro:"Hvad bliver først synligt, når en relation eller hændelse opstår?",cases:[
  {title:"Vandrende sort hul",status:"OBSERVATION",relations:["Hændelse","Manifestation","Efterspor"],finding:"Et objekt uden for galaksens centrum blev observerbart gennem sin relation til en forbipasserende stjerne.",counter:"Synliggørelse gennem en hændelse beviser ikke, at objektet kun eksisterer relationelt."},
  {title:"Solens skjulte magnetisme",status:"BEKRÆFTET",relations:["Bølge","Efterspor","Rekonstruktion"],finding:"Bølger i Solen kan bære information om magnetiske strukturer på den side, vi ikke ser direkte.",counter:"Det er en specifik inversionsmetode, ikke i sig selv en generel ontologisk konklusion."},
  {title:"Apophis 2029",status:"KANDIDAT",relations:["Perturbation","Forsinkelse","Residual"],finding:"Passagen tilbyder et testvindue for, hvordan påvirkning registreres i en tilstand, der allerede bevæger sig.",counter:"Kollision med højbanegenstande vurderes ekstremt usandsynlig; geometri er ikke prognose."},
  {title:"Timefold",status:"KANDIDAT",relations:["Forsinkelse","Overgang","Observation"],finding:"Hypotesen undersøger forskellen mellem hændelse, registrering og integration.",counter:"Ingen direkte empirisk bekræftelse; må forblive hypotese."}]},
 {id:"technology",glyph:"⌬",title:"Teknologi",subtitle:"M.E.M.I. & manifestationer",color:"#54e0d2",intro:"Samme beslutningskerne afprøvet i forskellige teknologiske former.",cases:[
  {title:"M.E.M.I. / Lillefisen",status:"BETINGET",relations:["Residual","Feedback","Recoverability"],finding:"En runtime, der beskytter levedygtige næste tilstande og kan afstå, undersøge eller stabilisere før handling.",counter:"Samme arkitektur på tværs af demoer er ikke det samme som domænevalidering."},
  {title:"ETOS & CDP",status:"BEKRÆFTET",relations:["Ansvar","Afståelse","Sporbarhed"],finding:"Beslutningsarkitekturen gør grænser, usikkerhed, ansvar og mulighed for tilbagevenden eksplicitte.",counter:"Bekræftet som dokumenteret arkitektur — ikke som universelt bedre outcome."},
  {title:"Maxi",status:"KANDIDAT",relations:["Sansning","Stabilisering","Nærvær"],finding:"En fysisk terapihund tænkt til at møde akut uro gennem berøring, lyd, bevægelse, lys og vibration uden krav om ord.",counter:"Prototype; effekt og sikkerhed kræver test med mennesker og relevante fagpersoner."},
  {title:"LRE",status:"KANDIDAT",relations:["Anker","Sporbarhed","Adgang"],finding:"En struktur, der kan bevare borgerens røde tråd på tværs af møder og systemskift.",counter:"Brugbarhed, databeskyttelse og institutionel integration mangler fuld afprøvning."}]},
 {id:"decisions",glyph:"↯",title:"Valg",subtitle:"Beslutninger & ansvar",color:"#ffb378",intro:"Et valg vurderes også på de veje, det lukker, og om systemet kan vende tilbage.",cases:[
  {title:"Afståelse som handling",status:"BEKRÆFTET",relations:["Afståelse","Usikkerhed","Ansvar"],finding:"Når evidensen ikke kan bære et sikkert valg, kan eksplicit afståelse bevare mulighedsrummet bedre end falsk sikkerhed.",counter:"Afståelse er ikke neutralt, når forsinkelse selv skaber skade."},
  {title:"Timing ≠ mekanisme",status:"BEKRÆFTET",relations:["Timing","Mekanisme","Afgrænsning"],finding:"At to ting følger hinanden i tid identificerer ikke i sig selv den mekanisme, der forbinder dem.",counter:"Reglen afviser ikke timing som evidens; den begrænser konklusionens styrke."}]},
 {id:"future",glyph:"∞",title:"Muligheder",subtitle:"Alternativet til nu",color:"#f3f0dd",intro:"Ikke et facit, men konsekvenserne af at begynde et andet sted.",cases:[
  {title:"Behov før form",status:"KANDIDAT",relations:["Betingelse","Manifestation","Ansvar"],finding:"Design begynder med det, der skal kunne vedligeholdes, før løsningen eller objektet låses.",counter:"Behov kan være konfliktende, fejlfortolkede eller ændre sig undervejs."},
  {title:"Relation før objekt",status:"KANDIDAT",relations:["Relation","Identitet","Manifestation"],finding:"Objekter undersøges som midlertidigt stabiliserede mønstre i relationer frem for helt selvberoende enheder.",counter:"Det er teoriens udgangspunkt — atlasets resultater skal afgøre, hvor langt det kan bære."}]}
];

const defs:Record<string,string>={"Betinget adgang":"Noget kan passere, men ikke alt og ikke under alle betingelser.","Passage–barriere":"Den samme struktur kan både standse og koncentrere bevægelse.","Spændingsretning":"Forskellen peger mod den næste sandsynlige forandring.","Residual":"Det, der ikke passer i modellen, returneres som information.","Feedback":"Et udfald kan begrænse eller åbne en senere tilstand.","Recoverability":"Evnen til at bevare eller genetablere levedygtige veje.","Udveksling":"Et system vedligeholdes gennem reguleret forskel og passage.","Manifestation":"Den midlertidige form, en relationel proces bliver synlig som.","Efterspor":"Det aftryk en gentaget relation efterlader.","Overgang":"Et felt, der ikke blot er den gamle eller den nye tilstand.","Stabilisering":"Aktiv vedligeholdelse af levedygtighed — ikke stilstand.","Gentagelse":"En relation optræder igen og former sin fremtidige sandsynlighed."};
const statuses:Status[]=["BEKRÆFTET","BETINGET","KANDIDAT","OBSERVATION","FROSSET","FALSIFICERET"];

const lenses=[
 {id:"human",glyph:"◉",name:"Mennesket",title:"Verden som genstand",text:"Vi opdeler, navngiver og betragter ofte verden udefra. Det gør præcis analyse mulig — men kan skjule den deltagelse, som gør observationen mulig.",sees:["Objekter","Kategorier","Lineær tid"]},
 {id:"dog",glyph:"◔",name:"Hunden",title:"Verden som nærvær",text:"Lugtens fortid ligger stadig i rummet. Stemning, bevægelse og kropslig retning træder frem før ordene. Verden er et levende spor, ikke et stillbillede.",sees:["Duftspor","Kropsretning","Relationel tryghed"]},
 {id:"tree",glyph:"♧",name:"Træet",title:"Verden som udveksling",text:"Lys, vand, svampe, jord og årstider er ikke omgivelser omkring træet; de er med til løbende at gøre træet muligt.",sees:["Gradienter","Kredsløb","Langsom tid"]},
 {id:"river",glyph:"≈",name:"Floden",title:"Verden som passage",text:"Form er erindret bevægelse. Hver bred og hvert sving bærer tidligere strømme, mens landskabet både leder vandet og selv bliver formet af det.",sees:["Passage","Modstand","Hysterese"]},
 {id:"system",glyph:"⌬",name:"Et kunstigt system",title:"Verden som mulighedsrum",text:"Tilstande, begrænsninger og næste handlinger træder frem. Det afgørende er ikke kun målet, men hvilke levedygtige veje beslutningen bevarer.",sees:["Tilstande","Usikkerhed","Recoverability"]},
 {id:"future",glyph:"∞",name:"Et endnu ukendt perspektiv",title:"Verden uden færdig kategori",text:"Hvad kan blive synligt, hvis sanserne, tidsskalaen eller relationen til omgivelserne er en anden end vores? Her må atlaset afstå fra at udfylde svaret.",sees:["Potentiale","Forskelle","Uafklaret"]}
];

export default function Home(){
 const[entered,setEntered]=useState(false),[lens,setLens]=useState(0);
 const[worldId,setWorldId]=useState<string|null>(null),[caseIndex,setCaseIndex]=useState(0),[relation,setRelation]=useState<string|null>(null),[mode,setMode]=useState<"universe"|"relations"|"perspectives"|"alternative"|"method">("universe"),[layer,setLayer]=useState<"finding"|"counter">("finding");
 const world=worlds.find(w=>w.id===worldId)??null;
 const relations=useMemo(()=>Array.from(new Set(worlds.flatMap(w=>w.cases.flatMap(c=>c.relations)))).sort(),[]);
 const related=relation?worlds.flatMap(w=>w.cases.filter(c=>c.relations.includes(relation)).map(c=>({world:w,case:c}))):[];
 const changeMode=(m:typeof mode)=>{setMode(m);setWorldId(null)};
 if(!entered)return <main className="threshold"><div className="gate-haze"/><section className="gate-copy"><p className="eyebrow">M.E.M. · ET ATLAS OVER MULIGE VIRKELIGHEDER</p><h1>Verden begynder<br/>ikke med formen.</h1><p>Før noget bliver synligt, er der betingelser. Relationer. En overgang. Du står ved en mulig indgang — ikke til et facit, men til en anden måde at gå på opdagelse.</p><button className="enter" onClick={()=>setEntered(true)}><span>Træd gennem porten</span><i>→</i></button><small>Du kan altid vende tilbage</small></section><section className="tree-map" aria-label="M.E.M.s tre lag"><div className="crown"><b>03</b><span>MANIFESTATION</span><small>Det, der bliver synligt</small></div><div className="trunk"><b>02</b><span>OVERGANG</span><small>Spænding · retning · mirakel</small></div><div className="roots"><b>01</b><span>RELATIONELT POTENTIALFELT</span><small>Betingelserne før formen</small></div></section></main>;
 return <main><header className="topbar"><button className="brand" onClick={()=>{setEntered(false);changeMode("universe")}}><b>M·E·M</b><span>UNIVERSET</span></button><nav>{[["universe","Verdener"],["relations","Relationer"],["perspectives","Perspektiver"],["alternative","Et andet udgangspunkt"],["method","Metode"]].map(([m,label])=><button key={m} className={mode===m?"active":""} onClick={()=>changeMode(m as typeof mode)}>{label}</button>)}</nav></header>
 {mode==="universe"&&!world&&<section className="hero"><div className="stars"/><div className="hero-copy"><p className="eyebrow">ET ATLAS OVER MULIGE VIRKELIGHEDER</p><h1>Hvad bliver synligt,<br/><em>hvis vi begynder et andet sted?</em></h1><p>Gå på opdagelse. Følg sporene. Se også det, der ikke holdt. Her gives intet facit — kun adgang til at undersøge forbindelserne.</p><span className="scrollhint">VÆLG EN VERDEN ↓</span></div><div className="universe"><div className="core"><span>RELATION</span><small>før form</small></div>{worlds.map((w,i)=><button key={w.id} className={`planet p${i}`} style={{"--planet":w.color} as React.CSSProperties} onClick={()=>{setWorldId(w.id);setCaseIndex(0);setLayer("finding")}}><b>{w.glyph}</b><span>{w.title}</span><small>{w.subtitle}</small></button>)}</div></section>}
 {mode==="universe"&&world&&<section className="world-view" style={{"--world":world.color} as React.CSSProperties}><button className="back" onClick={()=>setWorldId(null)}>← Tilbage til universet</button><div className="world-head"><span className="world-glyph">{world.glyph}</span><div><p className="eyebrow">{world.subtitle}</p><h1>{world.title}</h1><p>{world.intro}</p></div></div><div className="case-layout"><aside><p>SPOR I DENNE VERDEN</p>{world.cases.map((c,i)=><button key={c.title} className={i===caseIndex?"selected":""} onClick={()=>{setCaseIndex(i);setLayer("finding")}}><i className={`dot s-${c.status.toLowerCase()}`}/>{c.title}</button>)}</aside><article className="case-card"><div className="case-meta"><span className={`status s-${world.cases[caseIndex].status.toLowerCase()}`}>{world.cases[caseIndex].status}</span><span>SPOR {caseIndex+1}/{world.cases.length}</span></div><h2>{world.cases[caseIndex].title}</h2><div className="layer-switch"><button className={layer==="finding"?"active":""} onClick={()=>setLayer("finding")}>Hvad vi ser</button><button className={layer==="counter"?"active":""} onClick={()=>setLayer("counter")}>Hvad der begrænser</button></div><p className="finding">{world.cases[caseIndex][layer]}</p><div className="tags">{world.cases[caseIndex].relations.map(r=><button key={r} onClick={()=>{setRelation(r);changeMode("relations")}}>{r} ↗</button>)}</div></article></div></section>}
 {mode==="relations"&&<section className="panel"><p className="eyebrow">PÅ TVÆRS AF VERDENER</p><h1>Følg en relation</h1><p className="lead">Vælg en minimumsstruktur. Atlaset viser, hvor den optræder — uden at gøre forekomsterne identiske.</p><div className="relation-grid">{relations.map(r=><button key={r} className={relation===r?"selected":""} onClick={()=>setRelation(r)}><span>{r}</span><small>{defs[r]||"Et registreret relationsspor, der kan sammenlignes på tværs."}</small></button>)}</div>{relation&&<div className="thread"><p className="eyebrow">TVÆRGÅENDE SPOR</p><h2>{relation}</h2><p>{defs[relation]}</p><div className="thread-items">{related.map(({world:w,case:c})=><button key={w.id+c.title} style={{"--world":w.color} as React.CSSProperties} onClick={()=>{setMode("universe");setWorldId(w.id);setCaseIndex(w.cases.indexOf(c))}}><span>{w.glyph} {w.title}</span><b>{c.title}</b><small>{c.status}</small></button>)}</div></div>}</section>}
 {mode==="perspectives"&&<section className="panel perspective-panel"><p className="eyebrow">SAMME VIRKELIGHED · FORSKELLIGE INDGANGE</p><h1>Hvem er verden<br/>set herfra?</h1><p className="lead">Perspektivet er ikke et vindue uden betydning. Det afgør, hvilke forskelle der kan sanses, hvilken fortid der stadig virker, og hvilke handlinger der overhovedet bliver mulige.</p><div className="lens-stage"><div className="hysteresis-model"><div className="history-ring r1"><span>ERINDRET FORTID</span></div><div className="history-ring r2"><span>AKTUEL RELATION</span></div><div className="history-ring r3"><span>MULIGE NÆSTE</span></div><div className="lens-core"><i>{lenses[lens].glyph}</i><b>{lenses[lens].name}</b></div></div><article className="lens-card"><span className="eyebrow">PERSPEKTIV {String(lens+1).padStart(2,"0")}</span><h2>{lenses[lens].title}</h2><p>{lenses[lens].text}</p><div className="sees">{lenses[lens].sees.map(x=><span key={x}>{x}</span>)}</div><p className="lens-note">Dette er en invitation til at prøve et strukturelt perspektiv — ikke en påstand om præcis subjektiv oplevelse.</p></article></div><div className="lens-picker">{lenses.map((l,i)=><button key={l.id} className={lens===i?"selected":""} onClick={()=>setLens(i)}><i>{l.glyph}</i><span>{l.name}</span></button>)}</div><div className="hysteresis-explain"><p className="eyebrow">RELATIONEL HYSTERESE</p><h2>Verden nulstilles ikke mellem øjeblikke.</h2><p>Det, der kan ske nu, afhænger både af de aktuelle relationer og af den vej, systemet kom hertil ad. Derfor kan samme påvirkning føre til forskellige manifestationer — afhængigt af perspektiv, historie og adgang.</p></div></section>}
 {mode==="alternative"&&<section className="panel"><p className="eyebrow">TO BEGYNDELSESBETINGELSER</p><h1>Et andet udgangspunkt</h1><p className="lead">Ingen rød eller grøn side. Kun to steder at begynde — og de muligheder, de gør mere sandsynlige.</p><div className="comparison"><div className="compare-head"><span>DET VANTE UDGANGSPUNKT</span><i>↔</i><span>DET RELATIONELLE ALTERNATIV</span></div>{[["Objektet forklarer relationen","Relationen gør objektet muligt"],["Fejl skal fjernes","Spændingen kan være information"],["Kontrol skaber sikkerhed","Recoverability skaber robusthed"],["Identitet er fast","Identitet vedligeholdes relationelt"],["Negativt resultat er fiasko","Negativt resultat afgrænser virkeligheden"],["Mennesket står udenfor","Mennesket deltager i relationen"],["Form først","Behov og betingelser før form"]].map(([a,b],i)=><div className="compare-row" key={a}><p>{a}</p><span>{String(i+1).padStart(2,"0")}</span><p>{b}</p></div>)}</div><blockquote>“Vi fortæller ikke mennesker, hvad de skal tro. Vi viser, hvad vi fandt, hvad der ikke holdt, og hvad der bliver muligt fra et andet udgangspunkt.”</blockquote></section>}
 {mode==="method"&&<section className="panel"><p className="eyebrow">SÅDAN BESKYTTER ATLASSET FORSKELLEN</p><h1>Metoden er en del af resultatet</h1><p className="lead">Observation, fortolkning og evidens må ikke glide sammen. Derfor kan alle spor åbnes med både fund og begrænsning.</p><div className="method-flow">{[["01","Betingelser","Hvad er til stede før menneskelige betegnelser?"],["02","Relation","Hvad kan mødes, passere, påvirke eller afgrænse?"],["03","Gentagelse","Optræder strukturen uafhængigt og former den næste tilstand?"],["04","Efterspor","Hvad er synligt bagefter — og kunne andet forklare det?"]].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><div className="rules">{[["R4","Timing ≠ mekanisme","Rækkefølge alene identificerer ikke årsagen."],["∅","Negativt er et resultat","Falsificerede og frosne spor bliver stående."],["Δ","Residual returneres","Forskellen skal kunne begrænse en senere tilstand."],["?","Afståelse er tilladt","Atlaset siger uafklaret, når data ikke kan bære mere."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="legend"><h2>Statuslag</h2>{statuses.map(s=><div key={s}><i className={`dot s-${s.toLowerCase()}`}/><b>{s}</b><p>{({BEKRÆFTET:"Dokumenteret i det angivne, afgrænsede domæne.",BETINGET:"Holder under bestemte vilkår; mangler fortsat afprøvning.",KANDIDAT:"En formuleret forbindelse, der endnu skal testes.",OBSERVATION:"Noget registreret uden at gøre det til bevis.",FROSSET:"Et resultat, der ikke må omskrives efter udfaldet.",FALSIFICERET:"Den specifikke forventning holdt ikke."} as Record<Status,string>)[s]}</p></div>)}</div></section>}
 <footer><span>M.E.M. GLOBAL RELATIONS ATLAS</span><p>Et åbent kort over det, vi har set — og det, vi endnu ikke ved.</p><span>v0.1 · 2026</span></footer></main>
}
